# About
Hello! I am Thomas Capelle, Machine Learning engineer at [Weights and Biases](http://wandb.com) working on the AI Applied Team. I am responsible of keeping the [wandb/examples](http://github.com/wandb/examples) repository live and up to date. I also build content on ML-OPS, application of `wandb` to industry and fun deep learning in general. Previously I was using deep learning to solve short term forecasting for solar energy at [Steady Sun](http://steadysun.fr). I have a background in Urban Planning, Combinatorial Optimization, Transportation Economics and Applied Math.


I love contributing to OSS and the ML community!


## Experience
[2022-present] **ML Engineer** @[Weights and Biases](http://wandb.com)
- Improving use experience through examples in [wandb/examples](http://github.com/wandb/examples).
- Creating content for [fully-connected](https://wandb.com/fc) on how to make machine learning better.
- Help companies integrating wandb into their MLOPS workflows.

[2020-2021] **ML Engineer** @[Steady Sun](http://steadysun.fr)
- Developing of next version of short term forecasting algorithm based on sky imager.
- Integration of ML tools to the steadysun code base.
- R&D in Deep Learning for detection/segmentation and forecasting of sky images.
- Collaboration with NVDIA AI on deployement and production of DL models.

[2018-2020] **Research Engineer** @[INES CEA](http://cea.fr)
- Development of algorithms for failure detection in Photovoltaic Systems
- Deep Learning model for parameter regression for IV-curve of photovoltaic modules
- Thermal Image segmentation and classification model
- Project engineer and coordination for Franco-Chilean partnership, international cooperation with multidisciplinary laboratories.

[2017-2018] **Research Engineer** @[Inria](http://inria.fr)
- Integration of spatial models with air quality and forecast models.

[2013--2016] **PhD** équipe STEEP @[Inria](http://inria.fr)
- Development of mathematical frameworks for urban/transport model calibration
- Multidisciplinary team work (Engineers, Economists, Urbanists)
- Supervision of interns work
- International conferences and peer-reviewed publications

[2011] **Master Internship** @[CIRRELT - Polytech Montréal](https://www.cirrelt.ca/)
- Location and Routing modelling : Development of algorithms for logistics
- Implementation of a [Column Generation algorithm](https://www.sciencedirect.com/science/article/pii/S0377221718304740)

[2010] **Assistant Professor** @[Universidad de los Andes](http://www.uandes.cl)
- Analysis and Algebra for engineers

## Publications

The full list of my publications is available via [Google Scholar](https://scholar.google.com/citations?hl=en&user=54AmAVUAAAAJ&view_op=list_works&gmla=AJsN-F7KXg9I52kC7hCSnQgV_2MTcXiM1PuhuT_NEaE2x3tej2k7jhuagVXFkllIfU7LEkrYY_oBISUxD2LxrZ78F1NLsFmyEoO3Lfrqree5d3tRiPU94-s)

## Education

**PhD in Computer Science**, [Université de Grenoble](https://www.uga.fr) - *2017*

**MSc in Civil Engineering - Transport**, [Universidad de Chile](www.uchile.cl) - *2013*

**Mathematical Engineer**, [Universidad de Chile](https://www.dim.uchile.cl) - *2013*

## Languages

**Spanish** (mothertongue) - **French** (native) - **English** (full professional proficiency C1) 

- You can download my beautiful LaTeX CV [here](https://github.com/tcapelle/CV/releases/latest)
- My Kaggle profile [here](https://www.kaggle.com/tcapelle)
